"""
TerrainAdapter — the NEW ``@terrain`` def-only EntityAdapter
(unified-admin-crud Phase 4, task 8.1).

Terrain had no admin surface at all; this adapter gives it a
definition-only one under the unified grammar (Requirement 7.4):

- **Def scope only**: terrain is a pure map-generation/combat definition
  (there are no terrain "instances" — a tile's terrain is derived from the
  procedural map, not an admin-owned object), so every INSTANCE verb is
  opted out with a reason pointing at the ``def`` scope, and the full
  definition scope (``def list``/``def show``/``def set``/``def reset``/
  ``def diff``) is supported.
- **Overlay-backed writes**: ``def set``/``def reset`` land in the shared
  ``definitions_overrides.yaml`` overlay and trigger a validated
  ``DataRegistry.reload_all`` (``terrain`` is a required file, so the
  overlay merges and the change goes live on the next reload). A failed
  reload rolls the overlay back unchanged. NOTE: terrain changes only
  affect NEWLY generated/derived tiles — already-rendered map data is not
  retroactively rewritten by a reload; that matches how every other def
  edit applies on the next lazy read.
- **No existing resolver**: unlike items/buildings/techs/powerups, the
  DataRegistry has no ``resolve_terrain``; this adapter reuses the shared
  ``DataRegistry._resolve`` key/name/prefix matcher over the ``terrain``
  dict (keyed by ``terrain_type``, which is also the def's display name).

Registry access is LAZY so constructing and registering the adapter never
needs a booted server; tests inject a ``registry`` double.
"""

from __future__ import annotations

from typing import Any

from world.admin.adapters._def_only import DefOnlyAdapter
from world.admin.adapters._support import live_registry
from world.admin.types import FieldSpec

#: The def-only opt-out reasons for the instance verbs (Requirements 1.5,
#: 7.4), each pointing at the supported def-scope path.
_LIST_REASON = (
    "terrain is definition-only — there are no terrain instances to "
    "list; use 'def list' to see the terrain definitions"
)
_SPAWN_REASON = (
    "terrain is definition-only — tiles are generated by the procedural "
    "map, not spawned; use 'def set' to edit a terrain definition"
)
_SHOW_REASON = (
    "terrain has no per-instance admin surface; use 'def show <type>' "
    "to inspect a terrain definition"
)
_SET_REASON = (
    "terrain has no modifiable per-instance fields; use 'def set <type> "
    "<field> <value>' to change a terrain definition"
)
_DESTROY_REASON = (
    "terrain is definition-only and cannot be destroyed as instances; "
    "edit 'terrain.yaml' (or use 'def reset') to change a definition"
)


class TerrainAdapter(DefOnlyAdapter):
    """EntityAdapter for terrain (the ``@terrain`` def-only admin surface).

    The instance plane (``list``/``spawn``/``show``/``set``/``destroy``) is
    opted out and inherited from :class:`DefOnlyAdapter` as unreachable
    stubs; this class declares only the grammar contract and the
    definition scope.

    Tests may inject a registry double via ``registry``; production
    resolves the live ``DataRegistry`` lazily per call.
    """

    entity_key = "terrain"
    #: Overlay/definition domain (matches DataRegistry._REQUIRED_FILES).
    def_domain = "terrain"

    # --- grammar contract (design per-entity matrix row for @terrain) ---
    supported_verbs = frozenset({
        "def list", "def show", "def set", "def reset", "def diff",
    })
    opt_outs: dict[str, str] = {
        "list": _LIST_REASON,
        "spawn": _SPAWN_REASON,
        "show": _SHOW_REASON,
        "set": _SET_REASON,
        "destroy": _DESTROY_REASON,
    }
    extra_verbs: dict[str, str] = {}
    aliases: dict[str, str] = {}

    def __init__(self, registry: Any | None = None) -> None:
        self._registry = registry

    # ------------------------------------------------------------------ #
    #  Registry access (lazy — no live game required)
    # ------------------------------------------------------------------ #

    def _live_registry(self) -> Any | None:
        """Injected double, else services facade, else the singleton."""
        return live_registry(self._registry)

    # ------------------------------------------------------------------ #
    #  Field schemas
    # ------------------------------------------------------------------ #

    def definition_fields(self) -> dict[str, FieldSpec]:
        """Overridable ``def set`` fields, against real ``TerrainDef``
        fields. ``terrain_type`` is the identity and is not settable;
        ``passable``/``buildable`` are booleans (no ``bool`` FieldSpec
        kind) so they are read-only through ``def show`` and edited in
        ``terrain.yaml`` directly. Merged data still runs the full
        SchemaValidator + cross_validate on reload, so subtler invariants
        fail the reload, not the game."""
        specs = (
            FieldSpec(name="map_symbol", kind="str", perm="Admin"),
            FieldSpec(name="resource_type", kind="str", perm="Admin"),
            FieldSpec(name="vision_modifier", kind="int", perm="Admin"),
            FieldSpec(name="movement_modifier", kind="float", perm="Admin"),
            FieldSpec(name="defense_modifier", kind="float", perm="Admin"),
            FieldSpec(name="latitude_bias", kind="float", perm="Admin"),
            FieldSpec(name="latitude_min", kind="float", min_value=0.0,
                      max_value=1.0, perm="Admin"),
        )
        return {spec.name: spec for spec in specs}

    # ------------------------------------------------------------------ #
    #  Definition scope
    # ------------------------------------------------------------------ #

    def def_registry_dict(self) -> dict | None:
        """The live ``DataRegistry.terrain`` dict (merged registry, keyed
        by ``terrain_type``)."""
        registry = self._live_registry()
        terrain = getattr(registry, "terrain", None) if registry else None
        return terrain if isinstance(terrain, dict) else None

    def def_resolve(self, token: str) -> Any | None:
        """Resolve a definition token by ``terrain_type`` key / name /
        unambiguous prefix. There is no ``DataRegistry.resolve_terrain``,
        so this reuses the shared ``DataRegistry._resolve`` matcher over
        the ``terrain`` dict, with ``terrain_type`` as both the registry
        key and the display-name attribute (case-insensitive, spaces vs.
        underscores tolerant — Requirement 2.6). Falls back to an exact
        dict lookup for doubles exposing only the ``terrain`` dict."""
        terrain = self.def_registry_dict()
        if terrain is None:
            return None
        token = str(token or "").strip()
        if not token:
            return None
        try:
            from world.data_registry import DataRegistry

            tdef = DataRegistry._resolve(
                token, terrain, name_attr="terrain_type", key_upper=False
            )
            if tdef is not None:
                return tdef
        except Exception:  # noqa: BLE001 - fall back to exact lookup
            pass
        return terrain.get(token)
